# Utiliza "uv", un gestor de proyectos para python.
[project]
name = "hud-overlay"
version = "0.1.0"
description = "Fightsitck para GNU/Linux"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "evdev>=1.9.2",
    "pygame>=2.6.1",
]
